eb-rails/config/routes.rb
Rails.application.routes.draw do

  root 'main#show'
  get 'tweets/search' #~~ json

  get 'tweets/stream'
  post 'tweets' => 'tweets#create'

end

eb-rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def set_amazon_es
    # require 'patron'
    require 'faraday_middleware/aws_signers_v4'
    require 'elasticsearch'


    @es_client = Elasticsearch::Client.new url: Rails.application.config.es_host do |f|
      f.request :aws_signers_v4,
                credentials: Aws::Credentials.new(Rails.application.config.aws_access_key , Rails.application.config.aws_secret_access_key),
                service_name: 'es',
                region: 'us-east-1'
      # f.adapter :patron
      f.adapter  Faraday.default_adapter
    end

    puts ' + + + + + + + + + + + + + + +  '
    puts ' application.set_amazon_es'
    puts ' + + + + + + + + + + + + + + +  '
  end


end

eb-rails/app/controllers/main_controller.rb
require 'sse_manager'

class MainController < ApplicationController

  def show
    keyword = params[:keyword] || 'all'

    # search for specific type of tweets on ElasticSearch, size limit to 50
    set_amazon_es
    if keyword == 'all'
      result = @es_client.search index: Rails.application.config.es_index, body: { query: { match_all: { } }, size: 50 }
    else
      result = @es_client.search index: Rails.application.config.es_index, body: { filter: { type: { value: keyword } }, size: 50 }
    end

    @filteredTweets = result['hits']['hits'] #array
    @id = SSEManager.get_id
  end

end

eb-rails/app/controllers/tweets_controller.rb
require 'json'
require 'sse_manager'

class TweetsController < ApplicationController

  def search

    # the same to main#show
    indexstr = 'foo'

    keyword = params[:keyword] || 'all'
    puts keyword

    set_amazon_es
    if keyword == 'all'
      result = @es_client.search index: indexstr, body: { query: { match_all: { } }, size: 5 }
    else
      result = @es_client.search index: indexstr, body: { filter: { type: { value: keyword } }, size: 10 }
    end

    @filteredTweets = result['hits']['hits'] #array

    #json
  end



  skip_before_action :verify_authenticity_token

  # POST /tweets
  def create
    data =  request.body.read
    puts data
    ## no implementation of SNS subscription. check the log to subscript manually
    json = JSON.parse(data)
    message =  JSON.parse(json['Message'])
    send_to_es message
    SSEManager.publish message['tweet']
    render nothing: true
  end


  # Needed for response.stream/SSE
  include ActionController::Live

  def stream
    id = params[:id]
    msg = SSEManager.get_msg(id)
    response.headers['Content-Type'] = 'text/event-stream'
    sse = SSE.new(response.stream, retry: 5000, event: "message")
    begin
      if msg
        sse.write(msg, event: "message")
        sse.close
        puts id, msg
      else
        render nothing: true
      end
    rescue IOError
    ensure
      sse.close
    end

  end

  private

  TRACKLIST = ['concert', 'trip', 'running', 'party']

  def send_to_es(newtweet)
      set_amazon_es
      isFound = false
      TRACKLIST.each do |type|
        if newtweet['tweet'].downcase.include? type
          @es_client.index  index: Rails.application.config.es_index, type: type, body: newtweet
          puts type
          isFound = true
          break
        end
      end
      if !isFound # the coming tweet doesn't belong to any of the types
        puts newtweet['tweet']
      end
    end

end

eb-rails/app/helpers/application_helper.rb
module ApplicationHelper
end

eb-rails/app/helpers/main_helper.rb
module MainHelper
end

eb-rails/app/helpers/tweet_helper.rb
module TweetHelper

end

eb-rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Tweet Map</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

</head>

<body>

<%= yield %>


</body>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

</html>

eb-rails/app/views/main/show.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Tweet Map</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Search Keywords
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><a href="?keyword=concert">concert</a></li>
            <li><a href="?keyword=party">party</a></li>
            <li><a href="?keyword=trip">trip</a></li>
            <!--li class="divider"></li-->
            <li><a href="?keyword=running">running</a></li>
          </ul>
        </li>
        <li><a href="#">Settings</a></li>
      </ul>
      <!--form class="navbar-form navbar-right">
        <input type="text" class="form-control" placeholder="Search...">
      </form-->
    </div>
  </div>
</nav>

<div class="jumbotron" style="margin-bottom: 0px">
  <div class="container">
    <div id="map"></div>
  </div>
</div>

<!--div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-2 sidebar">
      <ul class="nav nav-sidebar">
        <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Analytics</a></li>
      </ul>
      <ul class="nav nav-sidebar">
        <li><a href="">Nav item</a></li>
        <li><a href="">More navigation</a></li>
      </ul>
    </div>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
      <div class="row placeholders">
      </div>
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>#</th>
              <th>Header</th>
              <th>Header</th>
              <th>Header</th>
              <th>Header</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1,001</td>
              <td>Lorem</td>
              <td>ipsum</td>
              <td>dolor</td>
              <td>sit</td>
            </tr>
            <tr>
              <td>1,015</td>
              <td>sodales</td>
              <td>ligula</td>
              <td>in</td>
              <td>libero</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div-->

<!-- ================================================== -->

<script>
  var sseid = <%= @id %>;
  var points = <%= raw @filteredTweets.to_json %> ;
</script>


<%= javascript_include_tag 'map' %>

<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDDhmjEizB3PyRpcPrKCaqg6ugtJJlFIw8&libraries=visualization&callback=initMap">
</script>

<%= javascript_include_tag 'sse', defer: true %>

eb-rails/app/views/tweetbak/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

eb-rails/app/views/tweetbak/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

eb-rails/app/views/tweetbak/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tweets</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

eb-rails/app/views/tweetbak/new.html.erb
<h1>New Tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

eb-rails/app/views/tweetbak/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>

eb-rails/app/views/tweets/submit.html.erb
<h1>Form  example</h1>
<br>

<form action="/tweets" method="post">
  <div>
    <label for="msg">Message:</label>
    <textarea id="msg" name="msg"></textarea>
  </div>
  <div class="button">
    <button type="submit">Send your message</button>
  </div>
</form>

<p>
  <button onclick="logger.clear()">Clear log</button>
  <button onclick="closeConnection()">Stop reconnections</button>
  <span id="connection">Connecting...<div></div></span>
</p>
<div class="border" id="log"></div>
<div class="border" id="right-panel"><div>The clock before is implemented using HTML5 <code>&lt;canvas&gt;</code> and
  </code><a href="http://www.html5rocks.com/tutorials/sse/basics/">Server-Sent Events</a>.
  The server's time is pushed to the client every 5 seconds using a single open connection.
  The server is set to break connections lasting longer than 10 seconds. However, the browser
  automatically reconnects SSEs ~3 seconds after dropped connections!</div>
  <canvas class="CoolClock::140:::showDigital" title="Server Sent Events are powering this clock"></canvas>
</div>